# Generated by Django 4.0.4 on 2022-04-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_likeofcomment_commentofcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentOfComment',
        ),
    ]
